about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - simrep
  - regions
  summary: Simple repeasts track from UCSC | name=sequence | score=alignment score
    | col 7 = period | col 8 = copy_num
  tags:
    data-version: 06-Mar-2014
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-simplerepeats
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
